export const MULTITENANT_MODULE_OPTIONS = Symbol('MULTITENANT_MODULE_OPTIONS');
export const TENANT_DATASOURCE_MANAGER = Symbol('TENANT_DATASOURCE_MANAGER');
export const TENANT_REPOSITORY_FACTORY = Symbol('TENANT_REPOSITORY_FACTORY');